### ISSUE TITLE
Food CSS Styling

### ISSUE THREAD

**Issue by ghost** [gwengibbes/com6338-module10-assignment10-gibbes-longo-avery#49]
Edited button and CSS for Food page

**Comment by gwengibbes** [comment]
Quick question- what button was this? On the Recipe generator page?

**Comment by ghost** [comment]
I just made a button in my JS. The styling was always on the site. Yes, its for the RG page after you type in a result. I have an ID called recipe results.

**Comment by gwengibbes** [comment]
Which js are you referring to? There is no "my" js- do you meant the "recipe generator" page?
I looked today and red seemed to be removed from the root. Last night when I committed it was still there.
Maybe you can show us when we meet later today.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ghost** [comment]
I only touched my page and the JS that is linked to my page. I did remove the red from the root last night. I thought we had agreed on solely the white. If it's affecting other elements, feel free to add it back. I don't have an issue with the color.

**Comment by gwengibbes** [comment]
I thought it was only the banner…?
Let’s make a decision on that when we meet.
I am on my phone right now so when I get to my computer for the mtg we can decide.

On another note, as it was a group project, I didn't think anyone had a specific page so I am not sure what you mean by my page... I assume that you mean the recipe generator page so that is where I am checking. I think we (as a group)made sure to ensure that everyone had a good number of contributions and didn't turn it into a "your" and "my" scenario. I actually remember ensuring that we added a few more issues to you, Jordan, yesterday, so I am just asking that we keep it collaborative.
We are nearly there! Yay!



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
