### ISSUE TITLE
Drop Boxes 

### ISSUE THREAD

**Issue by gwengibbes** [gwengibbes/com6338-module10-assignment10-gibbes-longo-avery#6]
Add drop boxes to the homepage.

**Comment by ElodieLongo** [comment]
I think we will ony need dropdown menus to pages 1 and 2, what do you think?

**Comment by gwengibbes** [comment]
Yes, I agree that we only need dropdown menus to pages 1 & 2

**Comment by ElodieLongo** [comment]
Today I added a select dropdown to page1 and it was already getting populated by the arrays I defined in the index.js file.

I see a dropdown with links in page1 html but what I added was a standard select (dropdown). I read that it is recommended to use that instead of a dropdown for browser compatibility. I will clone the repository tomorrow from my office to better check but frome the code, it seems to me different from what I had pushed today. Let me know if you changed that or if I will need to try pulling that again tomorrow in case it didn't work today. Thank you!

**Comment by gwengibbes** [comment]
I didn’t change anything.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ElodieLongo** [comment]
Ok, thanks a lot for letting me know, I thought there was already a pull
request for that, associated to issue 15.
Now you should see my pull request with the functioning select dropdown as
per issue 15.

Not sure what should be the next step now, should you review and merge that
branch?

On a side note, I also saw that they mentioned we should add enhancement as
a label to our issues.
Not sure how much this will be considered for our evaluation, but wanted to
mention, as I read it in our assignment's instructions.

Thank you! I'll touch base again tomorrow.
Elodie


Il giorno mar 14 nov 2023 alle ore 00:31 gwengibbes <
***@***.***> ha scritto:
